name: Tag package
on:
  push:
    branches:
      - production
      - staging
      - develop
      - test-1
      - test-2
      - test-3
      - test-4
      - test-5
      - test-6
      - test-7
      - test-8
      - test-9
      - test-10

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
      id-token: write # allow OIDC token for Infisical
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Fetch Verdaccio token from Infisical
        uses: Infisical/secrets-action@v1.0.7
        with:
          method: oidc
          domain: https://secrets.tastatur-und-maus.net
          identity-id: ${{ secrets.INFISICAL_IDENTITY_ID }}
          project-slug: ${{ secrets.INFISICAL_PROJECT_SLUG }}
          env-slug: prod
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ env.PIPELINE_AUTH_TOKEN }}
          tag: ${{ github.ref_name }}
          registry: https://npm.registry.zeitraum.io
