name: Tag package
on:
  push:
    branches:
      - production
      - staging
      - develop
      - test-1
      - test-2
      - test-3
      - test-4
      - test-5
      - test-6
      - test-7
      - test-8
      - test-9
      - test-10

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.PIPELINE_AUTH_TOKEN }}
          tag: ${{ github.ref_name }}
          registry: https://npm.registry.zeitraum.io
