name: Tag package
on:
  push:
    branches:
      - production
      - staging
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.PIPELINE_AUTH_TOKEN }}
          tag: ${{ github.ref_name }}
          registry: https://npm.registry.zeitraum.io
